<template>
  <WuiButtonGroup condensed>
    <WuiButton>Foo</WuiButton>
    <WuiButton>Bar</WuiButton>
  </WuiButtonGroup>
  <WuiButtonGroup
    stretch="wide"
    condensed
  >
    <WuiButton>Foo</WuiButton>
    <WuiButton>Bar</WuiButton>
  </WuiButtonGroup>
  <WuiButtonGroup
    stretch="full"
    condensed
  >
    <WuiButton>Foo</WuiButton>
    <WuiButton>Bar</WuiButton>
  </WuiButtonGroup>
</template>
