<template>
  <WuiCodeDemoRow>
    <WuiBadge
      value="14"
      variant="black"
    >
      <WuiAvatar
        src="/demo-content/user-insights-icons/users-1.svg"
        square
      />
    </WuiBadge>
    <WuiBadge
      point
      variant="danger"
    >
      <WuiAvatar
        src="/demo-content/user-insights-icons/users-1.svg"
        square
      />
    </WuiBadge>
    <WuiBadge
      point
      variant="success"
    >
      <WuiAvatar
        src="/demo-content/user-insights-icons/users-1.svg"
        square
      />
    </WuiBadge>
  </WuiCodeDemoRow>
</template>
